Add devise
rbd3/Blog-App2 pull request #9
Opened 2023-11-06 17:03 UTC by rbd3

# Change made :
👉 Make login required
👉 Use devise gem for authentication

2023-11-08 08:58 UTC, danmainah requested changes
Hi @rbd3 and @noelfoka , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Add devise gem and setup it up.
✔️ Modify the Signup and Login views to match the design given.

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-11-08 08:58 UTC, danmainah commented on app/views/devise/sessions/new.html.erb
> +<%= render "devise/shared/links" %>
- [ ] @Team Great work adding the login page, however the design slightly differs from the design given, check the comparison below:

Given Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://github.com/katarighe/blog-app/assets/61408860/e99fbec7-d31c-41b2-bd32-e6e01f9284bd) | ![image](https://github.com/rbd3/Blog-App2/assets/61408860/99b58dfa-d192-4184-9bb0-55f5ae942ee5)

2023-11-08 08:58 UTC, danmainah commented on app/views/devise/registrations/new.html.erb
> +<%= render "devise/shared/links" %>
- [ ] @Team Great work adding the registration page, however the design slightly differs from the design given , check the comparison below:

Given Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://github.com/katarighe/blog-app/assets/61408860/e99fbec7-d31c-41b2-bd32-e6e01f9284bd) | ![image](https://github.com/rbd3/Blog-App2/assets/61408860/cb818577-82e9-4610-a5de-ed2c69a9a38b)

2023-11-08 08:58 UTC, danmainah commented on app/views/devise/registrations/new.html.erb
> +<%= render "devise/shared/links" %>
- [ ] @Team I was unable to sign up as a new user even after filling are the fields in the form, am getting the error below, Kindly consider checking your devise setup to ensure the login and registration work correctly.
![image](https://github.com/rbd3/Blog-App2/assets/61408860/236ea538-53fa-403a-a1d9-c7454a7edf80)

2023-11-09 07:38 UTC, binhussen approved these changes
Hi @rbd3 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
![IApproveSimonCowellGIF (6)](https://github.com/rbd3/Blog-App2/assets/52010789/e93b100a-c3c6-444e-ab35-ac31987b1efb)

## Highlights
- Sticked Given wireframe ✔️
- Well Stractured Code ✔️
- Used Git flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-09 07:40 UTC, merged